### ISSUE TITLE
Enchant level select breaks on firefox

### ISSUE THREAD

**Issue by EthanZeigler** [kkchengaf/Minecraft-Enchantment-Order-Calculator#1]
Selecting the enchant level of a book does not work on firefox right now. The below error is in the console. All adblocking was disabled.

```Uncaught TypeError: e.data is not iterable
    <anonymous> https://kkchengaf.github.io/Minecraft-Enchantment-Order-Calculator/search.js:399
    EventListener.handleEvent* https://kkchengaf.github.io/Minecraft-Enchantment-Order-Calculator/search.js:397
search.js:399:36
```

Debugging shows this to be the current value of `e`.

![image](https://user-images.githubusercontent.com/9123320/194687235-f7e50606-d02d-477d-bb6f-7fa0901bea3c.png)

**Comment by kkchengaf** [comment]
bug fixed. issue close.
