### ISSUE TITLE
Advance Search not working

### ISSUE THREAD

**Issue by tungthechicken** [kkchengaf/Minecraft-Enchantment-Order-Calculator#8]
Mode 1 works fine, but Mode 2 only returns a red "advance search" text without any upgrade tree.
![image](https://github.com/user-attachments/assets/ab1b1ed4-11e0-4517-80cb-04ba6d805a9a)

**Comment by paperky** [comment]
There's a pull request (#6) that proposes to fix the Advanced Mode search, and I was able to verify that it works locally when run on a python `httpserver`.

wiger3 is also hosting their fork (which they're making the pr for) of this on github.io for testing, try that and see if it works for you

**Comment by tungthechicken** [comment]
Works wonderfully, thanks for your response.
